# Generated by Django 4.1.7 on 2023-03-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Groceries', 'Groceries'), ('Food', 'Food'), ('Travel', 'Travel'), ('Clothing', 'Clothing'), ('Transfer', 'Transfer'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
