# Generated by Django 4.1.6 on 2023-02-12 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='nordigen_user_id',
        ),
    ]
