# Generated by Django 4.1.7 on 2023-02-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_monthlyreport_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='year',
            field=models.IntegerField(default=2023),
            preserve_default=False,
        ),
    ]
