# Generated by Django 4.1.7 on 2023-02-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_monthlyreport_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='month',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
