# Generated by Django 4.1.7 on 2023-02-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_monthlyreport_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyreport',
            name='month',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='year',
            field=models.CharField(max_length=5),
        ),
    ]
