# Generated by Django 4.1.7 on 2023-02-27 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_monthlyreport_month_alter_monthlyreport_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.monthlyreport'),
        ),
    ]
