# Generated by Django 4.1.7 on 2023-02-27 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_monthlyreport_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyreport',
            name='month',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='month_year',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='year',
        ),
    ]
