# Generated by Django 4.1.7 on 2023-03-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_monthlyreport_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='info',
            field=models.TextField(blank=True, default=''),
        ),
    ]
